name: Daily Tibia EXP report

on:
  schedule:
    - cron: "45 10 * * *"
  workflow_dispatch:

jobs:
  run-exp-bot:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run EXP bot
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python tibia_exp.py

      - name: Save EXP history
        run: |
          git config --global user.name "tibia-exp-bot"
          git config --global user.email "tibia-exp-bot@users.noreply.github.com"

          git add exp_history.json

          git commit -m "Update EXP history" || exit 0

          git push
