name: GuildStats Bot

on:
  workflow_dispatch:

  schedule:
    - cron: "15 10 * * *"
    - cron: "15 22 * * *"


jobs:
  run-bot:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4


    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"


    - name: Install dependencies
      run: |
        pip install -r requirements.txt


    - name: Run GuildStats bot
      run: |
        python guildstats_bot.py


    - name: Save changes
      run: |
        git config --global user.name "guildstats-bot"
        git config --global user.email "bot@guildstats.local"

        git add .

        git commit -m "Update GuildStats data" || exit 0

        git push
